// 4. BONUS TASK
// - use JWT generated by /auth to authenticate all the routes above
// - create middleware to handle it
// - send the JWT any way you like

// note - split routes to private and public, protect private with checkToken middleware

const jwt = require('jsonwebtoken')

function checkToken (req, res, next) {
  const token = req.headers['x-access-token']

  if (token) {
    jwt.verify(token, process.env.JWT_SECRET, function (err, decoded) {
      if (err) {
        return res.json({ success: false, message: 'Failed to authenticate token.' })
      }
      req.decoded = decoded
      next()
    })
  } else {
    return res.status(403).send({
      success: false,
      message: 'No token provided.',
    })
  }
}

module.exports = {
  checkToken,
}
